name: main
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          rfbrowser init
      - name: robot framework
        run: |
          robot --listener allure_robotframework:results/allure --outputdir results --xunit xunit.xml tests

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: results/allure

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history