on:
  workflow_dispatch:
  
jobs:
  test:
    name: robot
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: python version
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: robot framework
      run: |
        robot --outputdir results --xunit xunit.xml tests
    - name: test results
      uses: dorny/test-reporter@v1
      with:
        name: robot results
        path: xunit.xml
        reporter: java-junit
    - name: upload results
      uses: actions/upload-artifact@v3
      with: 
        name: robot results
        path: results
