name: main
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 1 * * *'
  
jobs:
  test:
    name: robot
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: python version
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init
    - name: robot framework
      run: |
        robot --outputdir results --xunit xunit.xml tests
    - name: upload results
      uses: actions/upload-artifact@v4
      with: 
        name: robot results
        path: results
